In [13]:
import numpy as np


In [14]:
x = np.zeros((3,3))
a = np.array([2,2,3])
x[0,:] = a
print(x)

[[2. 2. 3.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
print(a.shape)


(3,)


In [24]:
a = np.array([1,2,3,4])
b = 1
c = np.insert(a,0,b)
print(c)

IndexError: index 5 is out of bounds for axis 0 with size 5